env:
  global:
  - PATH=$PATH:$HOME/.local/bin
language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler
- bundle outdated
jobs:
  include:
  - stage: Build
    if: ( type = push ) AND ( branch != master )
    script:
    - ./build
  - stage: Screenshot
    if: type = pull_request
    script:
    - ./build
    - ./serve &
    - npm install puppeteer
    - node screenshot.js
    - pip install --user awscli
    - aws s3 cp screenshot.png s3://builds.code.mil/$TRAVIS_BUILD_NUMBER/screenshot.png --acl public-read
    - "curl -H \"Authorization: token ${GITHUB_TOKEN}\" -X POST -d \"{\\\"body\\\": \\\"![${TRAVIS_BUILD_NUMBER}](https://s3-${AWS_DEFAULT_REGION}.amazonaws.com/builds.code.mil/${TRAVIS_BUILD_NUMBER}/screenshot.png)\\\"}\" \"https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments\""
  - stage: Deploy
    if: (( type = push ) AND ( branch = master )) OR ( tag =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$ )
    script:
    - ./build
    - if [[ -z "$TRAVIS_TAG" ]] ; then cp robots.txt-for-beta.code.mil _site/robots.txt ; fi
    - export BUCKET="www.code.mil"
    - if [[ -z "$TRAVIS_TAG" ]] ; then export BUCKET="beta.code.mil" ; fi
    deploy:
      provider: s3
      bucket: $BUCKET
      region: us-west-2
      local_dir: _site
      skip_cleanup: true
      acl: public_read
