language: ruby
cache: bundler
before_install:
- gem update --system
- gem install bundler
- bundle outdated
jobs:
  include:
  - stage: Build
    if: ( type = push ) AND ( branch != master )
    script:
    - ./build
  - stage: Deploy
    if: (( type = push ) AND ( branch = master )) OR ( tag =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$ )
    script:
    - ./build
    - if [[ -z "$TRAVIS_TAG" ]] ; then cp robots.txt-for-beta.code.mil _site/robots.txt ; fi
    - export BUCKET="www.code.mil"
    - if [[ -z "$TRAVIS_TAG" ]] ; then export BUCKET="beta.code.mil" ; fi
    deploy:
      provider: s3
      bucket: $BUCKET
      region: us-west-2
      local_dir: _site
      skip_cleanup: true
      acl: public_read
