dist: trusty
sudo: false
language: ruby
cache: bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
- gem update --system
script:
- "./cibuild"
deploy:
  before_deploy:
  - if [[ "$TRAVIS_TAG" =~ "^v[0-9]+\.[0-9]+\.[0-9]+$" ]] ; then export BUCKET="www.code.mil" ; else export BUCKET="beta.code.mil" ; fi
  provider: s3
  on:
    branch: master
  access_key_id: "$ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: $BUCKET
  local_dir: _site
  skip_cleanup: true
notifications:
  slack:
    secure: 4qPA2gwhnysIhyMOSN/9B30lANgIKvvoiL+0QC0UMeIOCbWj3l/HvKbnylONIyegbYdeJlJE21B4/Cs4wbeM637QYHwyRNqIpLNPOsb7fnZRcBaASa86wGwiOHWeKBxqxH2jb980t8T8otMFy3YcT/ipyDtCN2+d3DqmNgtfhcFmWKRBoZKnRda/HfxxCRxiOZpCCJg9SSOzeTx3yQ8En5vDg6KFfPAnUKVNYsy65yeb6IE4YUq9pJF/XQyE/yjsSluYyPnL0128kE3lI1KfxpGpi3dwQ/uRMBBrxWT9PDPl/jzVeHUccDCJgX5pWlKpgFmXdHMs7VjJUMEUTiXqkNsS+CI4HSELUw4UIn/oUWqZTBoty3ASYLsztlj4wed+ya6g2DFGvGFHzke6chDzHQqmGlLX59f4bl5XQPybFWpu5vCJYfI88ZupWslZDGuB2wYSlCLxizsXmA6Pv+pmixDPvtppEUkTd4+N+FWU+uKP6TFK5OGNIZ006qt8/uogn+C7rReiANfBP+K62xM3klsTTbSOVDRCLVjOVMpbORQ5t/wjZYljaitoxi1FCsmxK6QabZP+Wx7U0VhnB8PBArTVob2m9u2JCsRTndn2SrKUz01khxJPlO6d7hviu/PMdmsAtSTJx3oXsT/w2UGF3Lq1RAD7CkOLalDKGSIAqHI=
    on_success: change
    on_failure: always
