dist: trusty
sudo: false
language: ruby
cache: bundler
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
branches:
  only:
    - master
before_install:
  - gem update --system
script:
  - ./cibuild
deploy:
  provider: s3
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: code-dot-mil-website
  local_dir: _site
  skip_cleanup: true
